apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::897240014224:user/Sowmya
      username: <username>
      groups:
        - system:masters
