apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "deployapp3"
  namespace: "2048-game"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: "2048"
          ports:
            - containerPort: 80